apiVersion: batch/v1
kind: Job
metadata:
  name: even
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: even
        image: odd-even
        imagePullPolicy: Never
        command: [/even-amd64-linux]
      restartPolicy: Never
  backoffLimit: 4
